### PR TITLE
feat(): Update textures and implement ticking on snad and red_snad

### PR DESCRIPTION
**Pull request by RebelliousUno**
Implement Ticking based on TheRoBrit's original code 
Probably plenty of scope for updating and making more concise

### CODE REVIEW

**Comment by DarkMorford** [comment]
Overall this looks pretty good. There are a couple things that I think are unnecessary (removing the comments from `build.gradle`, for example) but those aren't dealbreakers.
What does concern me is that I have absolutely no experience with Kotlin. Converting the entire project greatly limits my ability to work on it, since I'd have to learn a whole new language while still getting up to speed with Minecraft's peculiarities. I don't know how feasible it is to have a mixed Kotlin/Java project, but maybe that's an option so we can both contribute?

**Comment by RebelliousUno** [comment]
You can easily just write a class in Java and use it in Kotlin and vice versa.  There's a few tweaks and the like I've had to make to get some stuff work that's a little weird in Minecraft, such as exposing the EnumType as a separate class (because ISerializableString requires for some reason you to extend getName() but because name is a member Kotlin will automatically create something akin to getName() and it has a bit of a cry) But then extending the Abstract version to bring in the EnumType worked nicely

Also removing the comments from build.gradle is me being a bit OCD,  there's a load of comments in there that just make the gradle file feel cluttered

https://kotlinlang.org/docs/reference/ is a good simple initial guide to the language and how the syntax gets made up.

**Comment by DarkMorford** [comment]
I'm not actually sure we even need that EnumType, to be honest. Since we're extending `BlockSand` instead of `BlockFalling`, we should be able to just use the one that vanilla Sand provides.
That said, I'm not sure how I want to go about merging this. I don't want to discount the work you've put in, but at the same time accepting the PR wholesale and then re-converting some stuff back to Java so I can work on it seems kinda silly. Any thoughts/ideas?

**Comment by RebelliousUno** [comment]
`BlockSand` also has the same Variant `EnumType`
Ok yes this is what I get when I extend `BlockSand`

```
Caused by: java.lang.IllegalArgumentException: Cannot set property PropertyEnum{name=variant, clazz=class net.minecraft.block.BlockSand$EnumType, values
=[sand, red_sand]} as it does not exist in BlockStateContainer{block=null, properties=[variant]}
```

**Comment by DarkMorford** [comment]
Hm, that's an odd thing to be seeing; I don't get any errors with the pure Java version, but I haven't implemented everything yet either.
You might want to try getting rid of the methods related to `BlockState`. I don't see any reason to implement them differently than `BlockSand`, so we might as well let the superclass do it instead of copying functionality.

**Comment by RebelliousUno** [comment]
The problem is that we need to have variants of the block to represent sand or red_sand.
Every block that extends `Block` has this `EnumType` on it.  I'll give it a go later just with a pure Java implementation of the block with the functionality to try extending `BlockSand`  

FWIW `BlockSand` extends `BlockFalling` extends `Block`

The other issue is that EnumType is static on BlockSand (basically it describes the variants of sand and meta data etc)

**Comment by RebelliousUno** [comment]
Ok I've refactored to extend `BlockSand`
the AbstractBlockSnad isn't being used atm so that can be removed actually as well

**Comment by RebelliousUno** [comment]
Reimplemented this is Java now. Will resolve conflicts after breakfast

**Pull request merged**
